[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#0B1120"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
